name: Build and Release Python Games

on:
  push:
    tags:
      - 'v*.*.*.*'  # Trigger on version tag pushes

permissions:
  contents: read

env:
  GAMES:
    pacman.py
    ping_pong.py
    貪食蛇.py
    六子棋.py
    そうこばん.py
    計算機.py

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.10]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build games with PyInstaller
        run: |
          for GAME in $GAMES; do
            pyinstaller --onefile "$GAME"
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: games-${{ matrix.os }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
